    location / {
        if ($ssl_client_verify = SUCCESS) {
            return 302 /mtls;
        }
        return 302 /ssl;
    }

    location /ssl {
        root   /V/sites/;
        index  index.html index.htm;
    }

    location /mtls {
        root   /V/sites/;
        index  index.html index.htm;
    }
    