FROM centos:8
MAINTAINER kusari-k

RUN sed -i -e "\$a fastestmirror=true" /etc/dnf/dnf.conf
RUN dnf update -y && \
	dnf install -y rsyslog samba && \
	dnf clean all


RUN echo "chroot_local_user=YES" >> /etc/vsftpd/vsftpd.conf && \
	echo "chroot_list_enable=YES" >> /etc/vsftpd/vsftpd.conf && \
	echo "pasv_address=$global_ip" >> /etc/vsftpd/vsftpd.conf && \
	echo "rsa_cert_file=/etc/letsencrypt/live/ftp.$domain/fullchain.pem" >> /etc/vsftpd/vsftpd.conf && \
	echo "rsa_private_key_file=/etc/letsencrypt/live/ftp.$domain/privkey.pem" >> /etc/vsftpd/vsftpd.conf && \
	echo "ssl_enable=YES" >> /etc/vsftpd/vsftpd.conf && \
	echo "pasv_min_port=10000" >> /etc/vsftpd/vsftpd.conf && \
	echo "pasv_max_port=10050" >> /etc/vsftpd/vsftpd.conf && \
	echo "require_ssl_reuse=NO" >> /etc/vsftpd/vsftpd.conf && \
	echo "user_config_dir=/etc/vsftpd/vsftp_user_conf" >> /etc/vsftpd/vsftpd.conf && \
	echo "allow_writeable_chroot=YES" >> /etc/vsftpd/vsftpd.conf && \
	echo "reverse_lookup_enable=NO" >> /etc/vsftpd/vsftpd.conf

COPY setting.log run.sh /usr/local/bin/

RUN sed -i -e "/imjournal/ s/^/#/" \
	-e "s/off/on/" \
	-e "s/var\/log/log\/log/g" /etc/rsyslog.conf


RUN  chmod 755 /usr/local/bin/run.sh
ENTRYPOINT ["/usr/local/bin/run.sh"]

#RUN mkdir /etc/vsftpd/vsftp_user_conf/
#RUN echo "" > /etc/vsftpd/chroot_list
