FROM centos:8
MAINTAINER kusari-k

ARG USER_DOMAIN
ARG SSL_DOMAIN
ARG GLOBAL_IP

RUN sed -i -e "\$a fastestmirror=true" /etc/dnf/dnf.conf
RUN dnf update -y && \
	dnf install -y rsyslog vsftpd passwd && \
	dnf clean all


RUN echo -e "chroot_local_user=YES" >> /etc/vsftpd/vsftpd.conf && \
	echo -e "chroot_list_enable=YES" >> /etc/vsftpd/vsftpd.conf && \
	echo -e "allow_writeable_chroot=YES" >> /etc/vsftpd/vsftpd.conf && \
	echo -e "chroot_list_file=/conf/vsftpd.chroot_list" >> /etc/vsftpd/vsftpd.conf && \
	echo -e "ssl_enable=YES" >> /etc/vsftpd/vsftpd.conf && \
	echo -e "require_ssl_reuse=NO" >> /etc/vsftpd/vsftpd.conf && \
	echo -e "rsa_cert_file=/etc/letsencrypt/live/$SSL_DOMAIN/fullchain.pem" >> /etc/vsftpd/vsftpd.conf && \
	echo -e "rsa_private_key_file=/etc/letsencrypt/live/$SSL_DOMAIN/privkey.pem" >> /etc/vsftpd/vsftpd.conf && \
	echo -e "pasv_address=$GLOBAL_IP" >> /etc/vsftpd/vsftpd.conf && \
	echo -e "pasv_min_port=20000" >> /etc/vsftpd/vsftpd.conf && \
	echo -e "pasv_max_port=20050" >> /etc/vsftpd/vsftpd.conf && \
	echo -e "better_stou=YES" >> /etc/vsftpd/vsftpd.conf && \
	echo -e "use_localtime=YES" >> /etc/vsftpd/vsftpd.conf && \
	echo -e "local_root=/usr/share/empty" >> /etc/vsftpd/vsftpd.conf && \
	echo -e "user_config_dir=/conf/vsftp_user_conf" >> /etc/vsftpd/vsftpd.conf && \
	echo -e "vsftpd_log_file=/log/vsftpd.log" >> /etc/vsftpd/vsftpd.conf && \
	echo -e "syslog_enable=YES" >> /etc/vsftpd/vsftpd.conf && \
	echo -e "reverse_lookup_enable=NO" >> /etc/vsftpd/vsftpd.conf && \
	sed -i -e "s/^#ascii/ascii/" \
		-e "/listen=/ s/NO/YES/" \
		-e "/listen_ipv6=/ s/YES/NO/" /etc/vsftpd/vsftpd.conf
RUN echo -e "log_ftp_protocol=YES" >> /etc/vsftpd/vsftpd.conf
RUN mkdir -p -m 444 /usr/share/empty && \
	echo -e "Setting is not completed ." > /usr/share/empty/README.txt && \
	echo -e "Please set /conf/vsftp_user_conf/USER_NAME ." >> /usr/share/empty/README.txt && \
	echo -e "You can't do anything ." >> /usr/share/empty/.message

COPY setting.log run-vsftp.sh /usr/local/bin/
COPY letsencrypt /etc/letsencrypt/

RUN chmod -R 777 /etc/letsencrypt

RUN sed -i -e "/imjournal/ s/^/#/" \
	-e "s/off/on/" \
	-e "s/var\/log/log\/log/g" /etc/rsyslog.conf


RUN  chmod 755 /usr/local/bin/run-vsftp.sh
ENTRYPOINT ["/usr/local/bin/run-vsftp.sh"]
