#!/bin/sh
# config.php の生成まで待機

SetupConfigFile() {

    while [ ! -e "/var/www/nextcloud/config/config.php" ]; do
        sleep 1
    done

    num=$(
        grep ^\$CONFIG -n /var/www/nextcloud/config/config.php |
            sed "s/:.*//g" |
            head -n 1
    )

    if [ $(cat /var/www/nextcloud/config/config.php | grep default_phone_region | wc -l) -eq 0 ]; then
        sed -i "${num} r /usr/local/src/config.php.txt" /var/www/nextcloud/config/config.php
    fi

}

chown root:root -R /var/www/nextcloud
chmod 775 /var/www/nextcloud/occ

SetupConfigFile &

exec php-fpm --allow-to-run-as-root
