#!/usr/bin/bash

DIR="/var/www/nextcloud"
occ="sudo -u www-data php $DIR/occ"
DB_NAME="nextcloud_db"
DB_USER="nextcloud_user"
DB_PASS="nextcloud_password"


chown -R www-data:www-data $DIR

# https://docs.nextcloud.com/server/latest/admin_manual/installation/command_line_installation.html
$occ  maintenance:install \
    --database='mysql' --database-name=$DB_NAME \
    --database-user=$DB_USER --database-pass=$DB_PASS \
    --admin-user='admin' --admin-pass='password'

# https://docs.nextcloud.com/server/latest/admin_manual/installation/installation_wizard.html#trusted-domain
$occ config:system:set 'trusted_domains' 1 --value '*'

# https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#default-phone-region
$occ config:system:set default_phone_region --value 'JP'

# https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#parameters
$occ config:system:set maintenance_window_start --value '1'

# https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
$occ config:system:set redis port --value '0'
$occ config:system:set redis host --value '/sock/redis.sock'
$occ config:system:set memcache.locking --value '\OC\Memcache\Redis'
$occ config:system:set memcache.distributed --value '\OC\Memcache\Redis'
$occ config:system:set memcache.local --value '\OC\Memcache\APCu'

$occ config:list
